// Code generated by protoc-gen-go. DO NOT EDIT.
// source: annoucement.proto

package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Annoucement struct {
	Id                   int64    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=Title,proto3" json:"Title,omitempty"`
	Content              string   `protobuf:"bytes,3,opt,name=Content,proto3" json:"Content,omitempty"`
	Url                  string   `protobuf:"bytes,4,opt,name=Url,proto3" json:"Url,omitempty"`
	CreateTime           int64    `protobuf:"varint,5,opt,name=CreateTime,proto3" json:"CreateTime,omitempty"`
	UpdateTime           int64    `protobuf:"varint,6,opt,name=UpdateTime,proto3" json:"UpdateTime,omitempty"`
	ExpiredTime          int64    `protobuf:"varint,7,opt,name=ExpiredTime,proto3" json:"ExpiredTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Annoucement) Reset()         { *m = Annoucement{} }
func (m *Annoucement) String() string { return proto.CompactTextString(m) }
func (*Annoucement) ProtoMessage()    {}
func (*Annoucement) Descriptor() ([]byte, []int) {
	return fileDescriptor_annoucement_8245a93a6d664f69, []int{0}
}
func (m *Annoucement) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Annoucement.Unmarshal(m, b)
}
func (m *Annoucement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Annoucement.Marshal(b, m, deterministic)
}
func (dst *Annoucement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Annoucement.Merge(dst, src)
}
func (m *Annoucement) XXX_Size() int {
	return xxx_messageInfo_Annoucement.Size(m)
}
func (m *Annoucement) XXX_DiscardUnknown() {
	xxx_messageInfo_Annoucement.DiscardUnknown(m)
}

var xxx_messageInfo_Annoucement proto.InternalMessageInfo

func (m *Annoucement) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Annoucement) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Annoucement) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Annoucement) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Annoucement) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *Annoucement) GetUpdateTime() int64 {
	if m != nil {
		return m.UpdateTime
	}
	return 0
}

func (m *Annoucement) GetExpiredTime() int64 {
	if m != nil {
		return m.ExpiredTime
	}
	return 0
}

func init() {
	proto.RegisterType((*Annoucement)(nil), "protos.Annoucement")
}

func init() { proto.RegisterFile("annoucement.proto", fileDescriptor_annoucement_8245a93a6d664f69) }

var fileDescriptor_annoucement_8245a93a6d664f69 = []byte{
	// 173 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4c, 0xcc, 0xcb, 0xcb,
	0x2f, 0x4d, 0x4e, 0xcd, 0x4d, 0xcd, 0x2b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x03,
	0x53, 0xc5, 0x4a, 0x07, 0x19, 0xb9, 0xb8, 0x1d, 0x11, 0xb2, 0x42, 0x7c, 0x5c, 0x4c, 0x9e, 0x29,
	0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0xcc, 0x41, 0x4c, 0x9e, 0x29, 0x42, 0x22, 0x5c, 0xac, 0x21, 0x99,
	0x25, 0x39, 0xa9, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x10, 0x8e, 0x90, 0x04, 0x17, 0xbb,
	0x73, 0x7e, 0x5e, 0x49, 0x6a, 0x5e, 0x89, 0x04, 0x33, 0x58, 0x1c, 0xc6, 0x15, 0x12, 0xe0, 0x62,
	0x0e, 0x2d, 0xca, 0x91, 0x60, 0x01, 0x8b, 0x82, 0x98, 0x42, 0x72, 0x5c, 0x5c, 0xce, 0x45, 0xa9,
	0x89, 0x25, 0xa9, 0x21, 0x99, 0xb9, 0xa9, 0x12, 0xac, 0x60, 0x93, 0x91, 0x44, 0x40, 0xf2, 0xa1,
	0x05, 0x29, 0x30, 0x79, 0x36, 0x88, 0x3c, 0x42, 0x44, 0x48, 0x81, 0x8b, 0xdb, 0xb5, 0xa2, 0x20,
	0xb3, 0x28, 0x35, 0x05, 0xac, 0x80, 0x1d, 0xac, 0x00, 0x59, 0x28, 0x09, 0xe2, 0x17, 0x63, 0x40,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xa3, 0x88, 0xa5, 0x9b, 0xe7, 0x00, 0x00, 0x00,
}
