// Code generated by protoc-gen-go. DO NOT EDIT.
// source: greeter.proto

package greeter

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GameCommand int32

const (
	GameCommand_Nothing     GameCommand = 0
	GameCommand_Hello       GameCommand = 1
	GameCommand_PushExample GameCommand = 2
)

var GameCommand_name = map[int32]string{
	0: "Nothing",
	1: "Hello",
	2: "PushExample",
}
var GameCommand_value = map[string]int32{
	"Nothing":     0,
	"Hello":       1,
	"PushExample": 2,
}

func (x GameCommand) String() string {
	return proto.EnumName(GameCommand_name, int32(x))
}
func (GameCommand) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_greeter_bfbe963e3b68733f, []int{0}
}

type Request struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_greeter_bfbe963e3b68733f, []int{0}
}
func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (dst *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(dst, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Response struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_greeter_bfbe963e3b68733f, []int{1}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type Message struct {
	PlayerId             int64    `protobuf:"varint,1,opt,name=PlayerId,proto3" json:"PlayerId,omitempty"`
	Ops                  int32    `protobuf:"varint,2,opt,name=Ops,proto3" json:"Ops,omitempty"`
	Data                 []byte   `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_greeter_bfbe963e3b68733f, []int{2}
}
func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (dst *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(dst, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetPlayerId() int64 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *Message) GetOps() int32 {
	if m != nil {
		return m.Ops
	}
	return 0
}

func (m *Message) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*Request)(nil), "Request")
	proto.RegisterType((*Response)(nil), "Response")
	proto.RegisterType((*Message)(nil), "Message")
	proto.RegisterEnum("GameCommand", GameCommand_name, GameCommand_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GreeterClient is the client API for Greeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GreeterClient interface {
	Hello(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type greeterClient struct {
	cc *grpc.ClientConn
}

func NewGreeterClient(cc *grpc.ClientConn) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) Hello(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/Greeter/Hello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GreeterServer is the server API for Greeter service.
type GreeterServer interface {
	Hello(context.Context, *Request) (*Response, error)
}

func RegisterGreeterServer(s *grpc.Server, srv GreeterServer) {
	s.RegisterService(&_Greeter_serviceDesc, srv)
}

func _Greeter_Hello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).Hello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Greeter/Hello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).Hello(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _Greeter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Hello",
			Handler:    _Greeter_Hello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "greeter.proto",
}

func init() { proto.RegisterFile("greeter.proto", fileDescriptor_greeter_bfbe963e3b68733f) }

var fileDescriptor_greeter_bfbe963e3b68733f = []byte{
	// 224 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x8f, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0xbb, 0x8d, 0x35, 0xc9, 0x44, 0x31, 0xcc, 0x29, 0x14, 0x95, 0x90, 0x53, 0xf4, 0x90,
	0x83, 0x82, 0x2f, 0xa0, 0x52, 0x45, 0xd4, 0xb2, 0x6f, 0x30, 0xd2, 0x21, 0x15, 0xb2, 0xd9, 0x98,
	0xd9, 0x80, 0xbe, 0xbd, 0xec, 0x1a, 0x7b, 0xfb, 0x86, 0xf9, 0x87, 0xf9, 0x3f, 0x38, 0x6d, 0x47,
	0x66, 0xc7, 0x63, 0x33, 0x8c, 0xd6, 0xd9, 0xea, 0x02, 0x62, 0xcd, 0x5f, 0x13, 0x8b, 0x43, 0x84,
	0xa3, 0x9e, 0x0c, 0x17, 0xaa, 0x54, 0x75, 0xaa, 0x03, 0x57, 0xe7, 0x90, 0x68, 0x96, 0xc1, 0xf6,
	0xc2, 0x98, 0x43, 0x64, 0xa4, 0x9d, 0xd7, 0x1e, 0xab, 0x17, 0x88, 0x5f, 0x59, 0x84, 0x5a, 0xc6,
	0x35, 0x24, 0xdb, 0x8e, 0x7e, 0x78, 0x7c, 0xde, 0x85, 0x44, 0xa4, 0x0f, 0xb3, 0x3f, 0x7c, 0x1f,
	0xa4, 0x58, 0x96, 0xaa, 0x5e, 0x69, 0x8f, 0xfe, 0xd5, 0x03, 0x39, 0x2a, 0xa2, 0x52, 0xd5, 0x27,
	0x3a, 0xf0, 0xf5, 0x1d, 0x64, 0x1b, 0x32, 0x7c, 0x6f, 0x8d, 0xa1, 0x7e, 0x87, 0x19, 0xc4, 0x6f,
	0xd6, 0xed, 0x3f, 0xfb, 0x36, 0x5f, 0x60, 0x0a, 0xab, 0x27, 0xee, 0x3a, 0x9b, 0x2b, 0x3c, 0x83,
	0x6c, 0x3b, 0xc9, 0xfe, 0xf1, 0x9b, 0xcc, 0xd0, 0x71, 0xbe, 0xbc, 0xb9, 0x82, 0x78, 0xf3, 0xa7,
	0x84, 0x97, 0x73, 0x0c, 0x93, 0x66, 0x96, 0x5a, 0xa7, 0xcd, 0x7f, 0xff, 0x6a, 0xf1, 0x71, 0x1c,
	0x9c, 0x6f, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0xd4, 0x5f, 0x71, 0x8c, 0x04, 0x01, 0x00, 0x00,
}
