// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2018-08-07 15:00:46.598665358 +0800 CST m=+0.048335660

package docs

import (
	"github.com/swaggo/swag"
)

var doc = `{
    "swagger": "2.0",
    "info": {
        "description": "howie",
        "title": "Golang Gin API",
        "termsOfService": "https://github.com/hwholiday/test",
        "contact": {},
        "license": {
            "name": "Howie",
            "url": "https://github.com/hwholiday/test"
        },
        "version": "1.0"
    },
    "paths": {
        "/v1/announcement/{id}": {
            "delete": {
                "produces": [
                    "application/json"
                ],
                "summary": "删除公告",
                "parameters": [
                    {}
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":400,\"data\":{},\"msg\":\"请求参数错误\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}`

type s struct{}

func (s *s) ReadDoc() string {
	return doc
}
func init() {
	swag.Register(swag.Name, &s{})
}
