// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from wire.go:

func NewApp() Msg3 {
	msg := NewMsg()
	msg2 := NewMsg2(msg)
	msg3 := NewMsg3(msg2)
	return msg3
}
