// Code generated by protoc-gen-go. DO NOT EDIT.
// source: msg.proto

package websocket

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//错误码
type STATUS int32

const (
	//0~99, 通用错误码
	STATUS_SUCCESS       STATUS = 0
	STATUS_UNKNOWN_ERROR STATUS = 1
)

var STATUS_name = map[int32]string{
	0: "SUCCESS",
	1: "UNKNOWN_ERROR",
}

var STATUS_value = map[string]int32{
	"SUCCESS":       0,
	"UNKNOWN_ERROR": 1,
}

func (x STATUS) String() string {
	return proto.EnumName(STATUS_name, int32(x))
}

func (STATUS) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{0}
}

// id 小于20的为保留协议 业务协议不能占用
//id = 1
type Ping struct {
	Times                int64    `protobuf:"varint,1,opt,name=Times,proto3" json:"Times,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ping) Reset()         { *m = Ping{} }
func (m *Ping) String() string { return proto.CompactTextString(m) }
func (*Ping) ProtoMessage()    {}
func (*Ping) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{0}
}

func (m *Ping) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ping.Unmarshal(m, b)
}
func (m *Ping) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ping.Marshal(b, m, deterministic)
}
func (m *Ping) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ping.Merge(m, src)
}
func (m *Ping) XXX_Size() int {
	return xxx_messageInfo_Ping.Size(m)
}
func (m *Ping) XXX_DiscardUnknown() {
	xxx_messageInfo_Ping.DiscardUnknown(m)
}

var xxx_messageInfo_Ping proto.InternalMessageInfo

func (m *Ping) GetTimes() int64 {
	if m != nil {
		return m.Times
	}
	return 0
}

//id = 2
type Pong struct {
	Times                int64    `protobuf:"varint,1,opt,name=Times,proto3" json:"Times,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pong) Reset()         { *m = Pong{} }
func (m *Pong) String() string { return proto.CompactTextString(m) }
func (*Pong) ProtoMessage()    {}
func (*Pong) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{1}
}

func (m *Pong) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pong.Unmarshal(m, b)
}
func (m *Pong) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pong.Marshal(b, m, deterministic)
}
func (m *Pong) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pong.Merge(m, src)
}
func (m *Pong) XXX_Size() int {
	return xxx_messageInfo_Pong.Size(m)
}
func (m *Pong) XXX_DiscardUnknown() {
	xxx_messageInfo_Pong.DiscardUnknown(m)
}

var xxx_messageInfo_Pong proto.InternalMessageInfo

func (m *Pong) GetTimes() int64 {
	if m != nil {
		return m.Times
	}
	return 0
}

//id = 3
type ErrorEx struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ErrorEx) Reset()         { *m = ErrorEx{} }
func (m *ErrorEx) String() string { return proto.CompactTextString(m) }
func (*ErrorEx) ProtoMessage()    {}
func (*ErrorEx) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{2}
}

func (m *ErrorEx) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ErrorEx.Unmarshal(m, b)
}
func (m *ErrorEx) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ErrorEx.Marshal(b, m, deterministic)
}
func (m *ErrorEx) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrorEx.Merge(m, src)
}
func (m *ErrorEx) XXX_Size() int {
	return xxx_messageInfo_ErrorEx.Size(m)
}
func (m *ErrorEx) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrorEx.DiscardUnknown(m)
}

var xxx_messageInfo_ErrorEx proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("gateway.STATUS", STATUS_name, STATUS_value)
	proto.RegisterType((*Ping)(nil), "gateway.Ping")
	proto.RegisterType((*Pong)(nil), "gateway.Pong")
	proto.RegisterType((*ErrorEx)(nil), "gateway.ErrorEx")
}

func init() { proto.RegisterFile("msg.proto", fileDescriptor_c06e4cca6c2cc899) }

var fileDescriptor_c06e4cca6c2cc899 = []byte{
	// 132 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcc, 0x2d, 0x4e, 0xd7,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4f, 0x4f, 0x2c, 0x49, 0x2d, 0x4f, 0xac, 0x54, 0x92,
	0xe1, 0x62, 0x09, 0xc8, 0xcc, 0x4b, 0x17, 0x12, 0xe1, 0x62, 0x0d, 0xc9, 0xcc, 0x4d, 0x2d, 0x96,
	0x60, 0x54, 0x60, 0xd4, 0x60, 0x0e, 0x82, 0x70, 0xc0, 0xb2, 0xf9, 0x38, 0x65, 0x39, 0xb9, 0xd8,
	0x5d, 0x8b, 0x8a, 0xf2, 0x8b, 0x5c, 0x2b, 0xb4, 0x34, 0xb8, 0xd8, 0x82, 0x43, 0x1c, 0x43, 0x42,
	0x83, 0x85, 0xb8, 0xb9, 0xd8, 0x83, 0x43, 0x9d, 0x9d, 0x5d, 0x83, 0x83, 0x05, 0x18, 0x84, 0x04,
	0xb9, 0x78, 0x43, 0xfd, 0xbc, 0xfd, 0xfc, 0xc3, 0xfd, 0xe2, 0x5d, 0x83, 0x82, 0xfc, 0x83, 0x04,
	0x18, 0x93, 0xd8, 0xc0, 0x0e, 0x30, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xc9, 0x56, 0x03, 0x3b,
	0x8d, 0x00, 0x00, 0x00,
}
